import { defineConfig } from "vitepress";

export default defineConfig({
  title: "NodomX Docs",
  description: "Documentation starter generated by create-nodomx.",
  themeConfig: {
    nav: [
      { text: "Guide", link: "/guide/getting-started" }
    ],
    sidebar: [
      {
        text: "Guide",
        items: [
          { text: "Getting Started", link: "/guide/getting-started" }
        ]
      }
    ]
  }
});
